// ui/src/Interface/Interfaces/Components/Notifications/Notification.svelte
<script lang="ts">
  import type { NotificationData } from '@shared/Models/NotificationData';
  import styles from '../../Styles/NotificationsInterface.module.css';
  import * as Icons from "lucide-svelte";
  import { NotificationType } from '@shared/Models/NotificationType';

  export let data: NotificationData;

  const defaultIcons: {
      [key in NotificationType]: string;
  } = {
      [NotificationType.Info]: 'Bell',
      [NotificationType.Warning]: 'AlertTriangle',
      [NotificationType.Error]: 'XCircle',
      [NotificationType.Success]: 'CheckCircle',
  }

  $: notificationClasses = [
      styles.notification,
      styles[data.type.toLowerCase()],
      data.hiding ? styles.hiding : ''
  ].filter(Boolean).join(' ');

  $: icon = data.icon ? data.icon : defaultIcons[data.type];
  $: iconFillOpacity = data.iconFillOpacity !== undefined ? data.iconFillOpacity : 0.1;
  $: IconComponent = (Icons as any)[icon.charAt(0).toUpperCase() + icon.slice(1).replace(/-([a-z])/g, (g: string) => g[1].toUpperCase())] || Icons.Bell;
  $: messageLines = data.message.split('\n');
</script>

<div class={styles.notificationWrapper}>
  <div class={notificationClasses}>
    <div class={styles.titleWrapper}>
      <svelte:component this={IconComponent} class={styles.title} fill="currentColor" fillOpacity={iconFillOpacity} size="1rem" />
      <span class={styles.title}>{data.title}</span>
    </div>
    <span class={styles.message}>
      {#each messageLines as line, index}
        <span>
          {line}
          {#if index < messageLines.length - 1}<br />{/if}
        </span>
      {/each}
    </span>
    <span class={styles.rightBar}></span>
  </div>
</div>

// ui/src/Interface/Interfaces/Components/Notifications/Notification.tsx
import type { NotificationData } from '@shared/Models/NotificationData';
import styles from '../../Styles/NotificationsInterface.module.css';
import * as Icons from "lucide-react";
import { NotificationType } from '@shared/Models/NotificationType';
// import { NotificationType } from '@shared/Models/NotificationType';

const defaultIcons: {
    [key in NotificationType]: string;
} = {
    [NotificationType.Info]: 'bell',
    [NotificationType.Warning]: 'alert-triangle',
    [NotificationType.Error]: 'x-circle',
    [NotificationType.Success]: 'check-circle',
}

export default function Notification({ data }: { data: NotificationData }) {
    const notificationClasses = [
        styles.notification,
        styles[data.type.toLowerCase()],
        data.hiding ? styles.hiding : ''
    ].filter(Boolean).join(' ');

    const icon = data.icon ? data.icon : defaultIcons[data.type];
    const iconFillOpacity = data.iconFillOpacity !== undefined ? data.iconFillOpacity : 0.1;
    const IconJSX = (Icons as any)[icon.charAt(0).toUpperCase() + icon.slice(1).replace(/-([a-z])/g, (g: string) => g[1].toUpperCase())] || Icons['Bell'];
    const message = data.message.split('\n').map((line, index) => (
        <span key={index}>
            {line}
            {index < data.message.split('\n').length - 1 && <br />}
        </span>
    ));

    return (
        <div className={styles.notificationWrapper}>
            <div className={notificationClasses}>
                <div className={styles.titleWrapper}>
                    <IconJSX className={styles.title} fill="currentColor" fillOpacity={iconFillOpacity} size="1rem"  />
                    <span className={styles.title}>{data.title}</span>
                </div>
                <span className={styles.message}>{message}</span>
                <span className={styles.rightBar}></span>
            </div>
        </div>
    )
}
