// ui/src/Interface/Interfaces/Components/Button.vue
<template>
  <div :class="wrapperClass" :style="{ ...style, ...wrapperStyle }">
    <!-- Glow effect - only for variants that support it -->
    <button 
      v-if="glow && (variant === 'primary' || variant === 'secondary' || variant === 'glass')"
      :class="glowClass"
      aria-hidden="true"
      tabindex="-1"
      :style="style"
    >
      <Loader2 v-if="loading" :size="'1rem'" :class="styles.spin" />
      <slot v-else />
    </button>
    
    <!-- Main button -->
    <button 
      v-bind="$attrs"
      :class="buttonClass"
      :style="style"
      :disabled="isDisabled"
    >
      <Loader2 v-if="loading" :size="'1rem'" :class="styles.spin" />
      <slot v-else />
    </button>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { Loader2 } from "lucide-vue-next";
import styles from './Button.module.css';
import csx from '../../../Utils/MergeClass';

interface Props {
  variant?: 'primary' | 'secondary' | 'dark' | 'glass' | 'ghost' | 'link' | 'gray';
  size?: 'small' | 'medium' | 'large';
  glow?: boolean;
  loading?: boolean;
  fullWidth?: boolean;
  wrapperStyle?: Record<string, any>;
  style?: Record<string, any>;
  disabled?: boolean;
  class?: string;
}

const props = withDefaults(defineProps<Props>(), {
  variant: 'primary',
  size: 'medium',
  glow: true,
  loading: false,
  disabled: false,
  fullWidth: false,
  class: ''
});

const buttonClass = computed(() => 
  `${styles.toneButton} ${styles[props.variant]} ${styles[props.size]} ${props.class}`
);

const glowClass = computed(() => 
  `${styles.glowEffect} ${styles[props.variant]}`
);

const isDisabled = computed(() => props.disabled || props.loading);

const wrapperClass = computed(() => 
  csx(
    styles.buttonWrapper,
    isDisabled.value ? styles.disabled : '',
    props.fullWidth ? styles.fullWidth : ''
  )
);
</script>

// ui/src/Interface/Interfaces/Components/Button.tsx
import type { ButtonHTMLAttributes, ReactNode } from 'react';
import * as Icons from "lucide-react";
import styles from './Button.module.css';
import csx from 'src/Utils/MergeClass';

interface ToneButtonProps extends ButtonHTMLAttributes<HTMLButtonElement> {
    children: ReactNode;
    variant?: 'primary' | 'secondary' | 'dark' | 'glass' | 'ghost' | 'link' | 'gray';
    size?: 'small' | 'medium' | 'large';
    glow?: boolean;
    loading?: boolean;
    fullWidth?: boolean;
}

export default function Button({ 
    children, 
    variant = 'primary', 
    size = 'medium',
    glow = true,
    loading = false,
    className = '',
    style,
    disabled,
    fullWidth = false,
    ...buttonProps
}: ToneButtonProps) {
    const buttonClass = `${styles.toneButton} ${styles[variant]} ${styles[size]} ${className}`;
    const glowClass = `${styles.glowEffect} ${styles[variant]}`;
    const isDisabled = disabled || loading;
    // const wrapperClass = `${styles.buttonWrapper} ${isDisabled ? styles.disabled : ''}`;
    const wrapperClass = csx(
        styles.buttonWrapper,
        isDisabled ? styles.disabled : '',
        fullWidth ? styles.fullWidth : ''
    );
    
    return (
        <div className={wrapperClass} style={style}>
            {/* Glow effect - only for variants that support it */}
            {glow && (variant === 'primary' || variant === 'secondary' || variant === 'glass') && (
                <button 
                    className={glowClass}
                    aria-hidden="true"
                    tabIndex={-1}
                    style={style}
                >
                    {loading ? <Icons.Loader2 size='1rem' className={styles.spin} /> : children}
                </button>
            )}
            
            {/* Main button */}
            <button 
                {...buttonProps}
                className={buttonClass}
                style={style}
                disabled={isDisabled}
            >
                {loading ? (
                    <Icons.Loader2 size='1rem' className={styles.spin} />
                ) : (
                    children
                )}
            </button>
        </div>
    );
}
