// ui/src/Interface/Interfaces/Components/InputField.vue
<template>
  <div :class="styles.inputGroup" :style="groupStyle">
    <label v-if="label">{{ label }}</label>
    <div :class="styles.inputWrapper">
      <slot name="icon" />
      <input
        v-bind="$attrs"
        :class="$attrs.class"
        :value="modelValue"
        @input="onInput"
      />
      <slot name="rightElement" />
    </div>
  </div>
</template>

<script setup lang="ts">
import styles from './InputField.module.css';

interface Props {
  label?: string;
  groupStyle?: Record<string, any>;
  modelValue?: string;
}

defineProps<Props>();

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void;
}>();

const onInput = (event: Event) => {
  const target = event.target as HTMLInputElement;
  emit('update:modelValue', target.value);
};
</script>

// ui/src/Interface/Interfaces/Components/InputField.tsx
import type { ReactNode, InputHTMLAttributes } from 'react';
import styles from './InputField.module.css';

interface InputFieldProps extends Omit<InputHTMLAttributes<HTMLInputElement>, 'onChange'> {
    icon?: ReactNode;
    label?: string;
    rightElement?: ReactNode;
    groupStyle?: React.CSSProperties;
    onChange: (value: string) => void;
}

export default function InputField({ 
    icon, 
    label,
    groupStyle,
    onChange,
    className,
    rightElement,
    ...inputProps
}: InputFieldProps) {
    return (
        <div className={styles.inputGroup} style={groupStyle}>
            {label && <label>{label}</label>}
            <div className={styles.inputWrapper}>
                {icon}
                <input
                    {...inputProps}
                    className={className}
                    onChange={(e) => onChange(e.target.value)}
                />
                {rightElement}
            </div>
        </div>
    );
}
