// ui/src/Interface/Interfaces/Components/Modal.tsx
import type { ReactNode } from 'react';
import * as Icons from 'lucide-react';
import styles from './Modal.module.css';

interface ModalProps {
    isOpen: boolean;
    onClose: () => void;
    title: string;
    children: ReactNode;
}

export default function Modal({ isOpen, onClose, title, children }: ModalProps) {
    if (!isOpen) return null;

    return (
        <div className={styles.modalOverlay} onClick={onClose}>
            <div className={styles.modalContent} onClick={(e) => e.stopPropagation()}>
                <div className={styles.modalHeader}>
                    <h2>{title}</h2>
                    <button className={styles.closeButton} onClick={onClose}>
                        <Icons.X size="1.2rem" />
                    </button>
                </div>
                <div className={styles.modalBody}>
                    {children}
                </div>
            </div>
        </div>
    );
}

// ui/src/Interface/Interfaces/Components/Modal.vue
<template>
  <div v-if="isOpen" :class="styles.modalOverlay" @click="onClose">
    <div :class="styles.modalContent" @click.stop>
      <div :class="styles.modalHeader">
        <h2>{{ title }}</h2>
        <button :class="styles.closeButton" @click="onClose">
          <X :size="20" />
        </button>
      </div>
      <div :class="styles.modalBody">
        <slot />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { X } from 'lucide-vue-next';
import styles from './Modal.module.css';

interface Props {
  isOpen: boolean;
  onClose: () => void;
  title: string;
}

defineProps<Props>();
</script>
