// ui/src/Interface/RageInterface.vue
<template>
  <div>
    <HudInterface v-if="isInterfaceVisible('HudInterface')" />
    <NotificationsInterface v-if="isInterfaceVisible('NotificationsInterface')" />
    <AuthInterface v-if="isInterfaceVisible('AuthInterface')" />
    <SpawnSelectionInterface v-if="isInterfaceVisible('SpawnSelectionInterface')" />
    <ScoreboardInterface v-if="isInterfaceVisible('ScoreboardInterface')" />
    <HandlingEditorInterface v-if="isInterfaceVisible('HandlingEditorInterface')" />
    <AtmInterface v-if="isInterfaceVisible('AtmInterface')" />
    <MapDemoInterface v-if="isInterfaceVisible('MapDemoInterface')" />
    <TextureDebugInterface v-if="isInterfaceVisible('TextureDebugInterface')" />
    <ChatInterface v-if="isInterfaceVisible('ChatInterface')" />
    <WorldInteractionInterface v-if="isInterfaceVisible('WorldInteractionInterface')" />
    <CharacterCreatorInterface v-if="isInterfaceVisible('CharacterCreatorInterface')" />
    <TopsMakerInterface v-if="isInterfaceVisible('TopsMakerInterface')" />
  </div>
</template>

<script setup lang="ts">
import { useInterfaceVisibility } from '../Hooks/InterfaceVisibilityProvider';
import NotificationsInterface from './Interfaces/NotificationsInterface.vue';
import AuthInterface from './Interfaces/AuthInterface.vue';
import SpawnSelectionInterface from './Interfaces/SpawnSelectionInterface.vue';
import HudInterface from './Interfaces/HudInterface.vue';
import ScoreboardInterface from './Interfaces/ScoreboardInterface.vue';
import HandlingEditorInterface from './Interfaces/HandlingEditorInterface.vue';
import AtmInterface from './Interfaces/AtmInterface.vue';
import MapDemoInterface from './Interfaces/MapDemoInterface.vue';
import TextureDebugInterface from './Interfaces/TextureDebugInterface.vue';
import ChatInterface from './Interfaces/ChatInterface.vue';
import WorldInteractionInterface from './Interfaces/WorldInteractionInterface.vue';
import CharacterCreatorInterface from './Interfaces/CharacterCreatorInterface.vue';
import TopsMakerInterface from './Interfaces/TopsMakerInterface.vue';

const { isInterfaceVisible } = useInterfaceVisibility();
</script>

// ui/src/Interface/RageInterface.tsx
import { useInterfaceVisibility } from "../Hooks/InterfaceVisibilityProvider";
import Providers from "../Hooks/Providers";
import NotificationsInterface from "./Interfaces/NotificationsInterface";
import AuthInterface from "./Interfaces/AuthInterface";
import SpawnSelectionInterface from "./Interfaces/SpawnSelectionInterface";
import HudInterface from "./Interfaces/HudInterface";
import ScoreboardInterface from "./Interfaces/ScoreboardInterface";
import HandlingEditorInterface from "./Interfaces/HandlingEditorInterface";
import AtmInterface from "./Interfaces/AtmInterface";
import InteractionWheelInterface from "./Interfaces/InteractionWheelInterface";
import MapDemoInterface from "./Interfaces/MapDemoInterface";
import TextureDebugInterface from "./Interfaces/TextureDebugInterface";
import ChatInterface from "./Interfaces/ChatInterface";

function Interfaces() {
    const { visibleInterfaces } = useInterfaceVisibility();
    const isInterfaceVisible = (name: string) => {
        return visibleInterfaces[name];
    };

    return (
        <>
            {/* Define here all the interface elements */}
            {isInterfaceVisible("HudInterface") && <HudInterface key="HudInterface" />}
            {isInterfaceVisible("NotificationsInterface") && <NotificationsInterface key="NotificationsInterface" />}
            {isInterfaceVisible("AuthInterface") && <AuthInterface key="AuthInterface" />}
            {isInterfaceVisible("SpawnSelectionInterface") && <SpawnSelectionInterface key="SpawnSelectionInterface" />}
            {isInterfaceVisible("ScoreboardInterface") && <ScoreboardInterface key="ScoreboardInterface" />}
            {isInterfaceVisible("HandlingEditorInterface") && <HandlingEditorInterface key="HandlingEditorInterface" />}
            {isInterfaceVisible("AtmInterface") && <AtmInterface key="AtmInterface" />}
            {isInterfaceVisible("InteractionWheelInterface") && <InteractionWheelInterface key="InteractionWheelInterface" />}
            {isInterfaceVisible("MapDemoInterface") && <MapDemoInterface key="MapDemoInterface" />}
            {isInterfaceVisible("TextureDebugInterface") && <TextureDebugInterface key="TextureDebugInterface" />}
            {isInterfaceVisible("ChatInterface") && <ChatInterface key="ChatInterface" />}
        </>
    )
}

export default function RageInterface() {
    return (
        <div>
            <Providers>
                <Interfaces />
            </Providers>
        </div>
    );
}
